### PR TITLE
Fix shimple issues with traps

### LINKED ISSUE #1678: Shimple uninitialized registers
**Describe the bug**
Run Soot with ```-via-shimple``` option on ```PhiNodeTestInput.java``` and the generated class file causes ```java.lang.VerifyError: (class: soot/shimple/PhiNodeTestInput, method: sync signature: ()Z) Accessing value from uninitialized register 7``` when loaded into the JVM.

**Input file**
The input file and a Soot framework test case for can be found in this commit https://github.com/tim-hoffman/soot/commit/b31481667c0e87847d96c6c2cb8204dc6d9c4a1c

**To reproduce**
Option 1: Checkout the commit mentioned above and run the test case via the Soot test build and observe the test failures. 
Option 2: Just download the ```PhiNodeTestInput``` file and on command line run
```java -cp <soot-jar-and-dependencies> soot.Main -pp -cp systemTest-target-classes -via-shimple soot.shimple.PhiNodeTestInput``` and then run ```java -cp sootOutput soot.shimple.PhiNodeTestInput``` and observe the VerifyError.

**Expected behavior**
Running the Soot-modified version of PhiNodeTestInput should simply print ```false``` and terminate normally instead of terminating with a VerifyError.

**Additional context**
The ```PhiNodeTest#testComplexPhi``` case is set up to run Soot on the input file, run several of the Soot built-in validators, and then attempt to load the generated class file, causing the VerifyError to occur. You may have to comment out the ```Assert.assertTrue(exceptions.isEmpty())``` line to see the JVM try to load the class since the Soot Validators may detect the issue and trigger that assertion. The ```DEBUG_PRINT``` flag can be set as ```true``` to print the Soot Validator messages.

The ```PhiNodeTest#testStdLib``` case is set up to run Soot on a selection of standard JRE classes that are known to cause the same issue. It runs Soot on all of those classes without using ```-via-shimple``` to show that there are no issues in that case and then runs again with the ```-via-shimple``` option set to true to show that the generated bytecode is invalid in that case. There is also a ```USE_ASM_VERIFIER``` flag in that file that can be set as ```true``` to use ASM to verify the generated bytecode instead of loading the generated classes into the JRE. This allows the test to run on some additional classes in the ```java.*``` package which could not be tested via the other approach (due to the ClassLoader restriction on the java.* package).

### PR DESCRIPTION
**Pull request by MarcMil**
Contains and fixes all test cases in https://github.com/soot-oss/soot/pull/1680
Also incorporates the test cases in https://github.com/soot-oss/soot/pull/1662
Fixes https://github.com/soot-oss/soot/issues/1678

### CODE REVIEW

File: src/main/java/soot/shimple/internal/PhiNodeManager.java [hunk 1]
```diff
@@ -361,83 +377,111 @@ public boolean dominates(Unit champ, Unit challenger) {
...
+          AssignStmt stmt = jimp.newAssignStmt(lhsLocal, p.getValue());
+          insertedStatements.add(stmt);
+          Value l = p.getValue();
+          if (l instanceof Local) {
+            List<Unit> ld = localDefs.getDefsOfAt((Local) l, pred);
+            assert ld.size() == 1;
+            Unit elem = ld.get(0);
+            //When the definition site happens to be in a loop, we cannot
+            //move the definition back, since otherwise we might destory
+            //the reference from thje previous iteration
```
Comment (StevenArzt) [inline src/main/java/soot/shimple/internal/PhiNodeManager.java]: typo: ``thje``

File: src/main/java/soot/shimple/internal/PhiNodeManager.java [hunk 2]
```diff
@@ -361,83 +377,111 @@ public boolean dominates(Unit champ, Unit challenger) {
...
+          }
+          AssignStmt stmt = jimp.newAssignStmt(lhsLocal, p.getValue());
+          insertedStatements.add(stmt);
+          Value l = p.getValue();
+          if (l instanceof Local) {
+            List<Unit> ld = localDefs.getDefsOfAt((Local) l, pred);
+            assert ld.size() == 1;
+            Unit elem = ld.get(0);
+            //When the definition site happens to be in a loop, we cannot
+            //move the definition back, since otherwise we might destory
```
Comment (StevenArzt) [inline src/main/java/soot/shimple/internal/PhiNodeManager.java]: typo: ``destory``

File: src/main/java/soot/shimple/internal/PhiNodeManager.java [hunk 3]
```diff
@@ -361,83 +377,111 @@ public boolean dominates(Unit champ, Unit challenger) {
...
-    if (equivStmts.size() != predBoxes.size()) {
-      throw new RuntimeException("Assertion failed.");
-    }
+          // if we need to insert the copy statement *before* an
+          // instruction that happens to be *using* the Local being
+          // defined, we need to do some extra work to make sure we
+          // don't overwrite the old value of the local
+          if (pred.branches()) {
+            boolean needPriming = false;
+            Local savedLocal = jimp.newLocal(lhsLocal.getName() + "_", lhsLocal.getType());
```
Comment (StevenArzt) [inline src/main/java/soot/shimple/internal/PhiNodeManager.java]: It would be better to check for naming duplicates, e.g., using ``LocalGenerator``.

File: src/main/java/soot/shimple/internal/PhiNodeManager.java [hunk 4]
```diff
@@ -361,83 +377,111 @@ public boolean dominates(Unit champ, Unit challenger) {
...
 
-        if (needPriming) {
-          body.getLocals().add(savedLocal);
-          units.insertBefore(jimp.newAssignStmt(savedLocal, lhsLocal), pred);
+            // this is all we really wanted to do!
+            units.insertBefore(stmt, pred);
+          } else {
+            Unit succ = pred;
+            while (true) {
+              Unit s = units.getSuccOf(succ);
```
Comment (StevenArzt) [inline src/main/java/soot/shimple/internal/PhiNodeManager.java:449]: You should check whether there is no successor anymore to avoid infinite loops on malformed Jimple bodies.

**Review by StevenArzt — APPROVED** [review]

File: src/main/java/soot/shimple/internal/PhiNodeManager.java (hunk 4 above)
Comment (MarcMil) [reply src/main/java/soot/shimple/internal/PhiNodeManager.java:449]: How is this supposed to work? We are going along the unit chain, at the end there is a ```null``` and we break out.

Comment (StevenArzt) [reply src/main/java/soot/shimple/internal/PhiNodeManager.java:449]: OK, due to the ``instanceof`` failing in that case.

Comment (MarcMil) [reply src/main/java/soot/shimple/internal/PhiNodeManager.java:449]: Correct
